### ISSUE TITLE
image size cannot be changed

### ISSUE THREAD

**Issue by bastelfreak** [andrewboring/alarm-images#5]
From the create-image script:

```bash
# Grab the first two arguments, using the defaults if not set
# This allows running the command as any of
#   ./create-image                 # to use the defaults
#   ./create-image 4G              # create a 4 gig image instead of 2 gig
#   ./create-image 4G myname.img   # create a 4 gig image called myname.img
size="8G"
```

while the comment implies that the image size can be changed, the parameter is actually used to determine the rpi version. the image size is hardcoded.

**Comment by andrewboring** [comment]
Sorry, I haven't been on top of this project lately. I'm finally giving it some much-needed attention. 
The newest commit has a fixed version of the script.

I've un-hardcoded the size parameter, updated the comments,  and added a little bit to the README to show positional usage (create-image [arch] [size]). Keep in mind, it's not very robust (if you use 8GB instead of 8G, for example). Need to add some sanity checking.
